global:
  tls:
    enabled: true
  domain: consul
  datacenter: dc2
  peering:
    enabled: true
  acls:
    manageSystemACLs: true
  # imageK8S: "ndhanushkodi/consul-k8s-dev:latestnov3"
  # image: "hashicorppreview/consul:1.14-dev"
server:
  replicas: 3
  bootstrapExpect: 3
  extraConfig: |
    {
      "log_level": "TRACE"
    }


ui:
  enabled: true

connectInject:
  enabled: true

controller:
  enabled: true

meshGateway:
  enabled: true
  replicas: 1
