apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
  name: nitya-fake
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8503
    protocol: TCP
    targetPort: 8503
  selector:
    app: consul
    component: server
  sessionAffinity: None
