---
# Service to expose backend
apiVersion: v1
kind: Service
metadata:
  name: backend2
spec:
  selector:
    app: backend2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend2
---
# deployment for backend2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "false"
    spec:
      serviceAccountName: backend2
      containers:
      - name: backend2
        image: nicholasjackson/fake-service:v0.22.4
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "backend2"
        - name: "MESSAGE"
          value: "Response from backend2"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: backend2
spec:
  protocol: "http"
# ---
# apiVersion: consul.hashicorp.com/v1alpha1
# kind: ServiceIntentions
# metadata:
#   name: backend
# spec:
#   destination:
#     name: backend
#   sources:
#     - name: frontend
#       action: allow
